# Generated by Django 5.2.16 on 2026-07-10 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_personal_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(blank=True, max_length=20, null=True)),
                ('stream_or_course', models.CharField(blank=True, max_length=20, null=True)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('score_type', models.CharField(blank=True, max_length=20, null=True)),
                ('score_value', models.FloatField(blank=True, max_length=10, null=True)),
                ('start_year', models.DateField(blank=True, null=True)),
                ('end_year', models.DateField(blank=True, null=True)),
                ('edu_image', models.ImageField(blank=True, null=True, upload_to='edu_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('start_year', models.DateField(blank=True, null=True)),
                ('end_year', models.DateField(blank=True, null=True)),
                ('internship_image', models.ImageField(blank=True, null=True, upload_to='internship_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Technical_Skils',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('skill_name', models.CharField(blank=True, max_length=50, null=True)),
                ('skill_image', models.ImageField(blank=True, null=True, upload_to='skill_image/')),
            ],
        ),
        migrations.AlterField(
            model_name='personal_information',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal_information',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personal_information',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personal_information',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal_information',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personal_information',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal_information',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal_information',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal_information',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personal_information',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal_information',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personal_information',
            name='tagline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Key_Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('technologies', models.TextField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, max_length=50, null=True)),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='project_image/')),
                ('internship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.internship')),
            ],
        ),
    ]
