# Generated by Django 5.2.16 on 2026-07-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_certifications_education_internship_technical_skils_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technical_skils',
            name='category',
            field=models.CharField(blank=True, choices=[('Web Frameworks', 'Web Frameworks'), ('Libraries', 'Libraries'), ('Frontend', 'Frontend'), ('Languages', 'Languages'), ('Database', 'Database'), ('Tools', 'Tools')], max_length=50, null=True),
        ),
    ]
