# Generated by Django 5.2 on 2026-07-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_technical_skils_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='technical_skils',
            name='proficiency',
            field=models.IntegerField(default=0, help_text='Skill proficiency percentage (0-100)'),
        ),
    ]
