# Generated by Django 5.2.16 on 2026-07-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_technical_skils_proficiency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extracurricular_Activities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('event_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('year', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
