# Generated by Django 5.2.16 on 2026-07-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='key_projects',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
