# Generated by Django 5.2.16 on 2026-07-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_key_projects_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key_projects',
            name='project_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
