# Generated by Django 5.2.16 on 2026-07-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_key_projects_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_information',
            name='resume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
